# Generated by Django 5.2.4 on 2025-07-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='CreatedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='sub_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Product.subvariant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Product.products'),
        ),
        migrations.AddField(
            model_name='subvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Product.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('ProductCode', 'ProductID')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['sub_variant', 'created_date'], name='products_st_sub_var_3eb6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'name'], name='products_va_product_9c809a_idx'),
        ),
        migrations.AddIndex(
            model_name='subvariant',
            index=models.Index(fields=['variant', 'value'], name='products_su_variant_d12c7c_idx'),
        ),
    ]
