# Generated by Django 5.2.4 on 2025-07-26 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='products_st_sub_var_3eb6d1_idx',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='created_date',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='subvariant',
            old_name='created_date',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='created_date',
            new_name='CreatedDate',
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['sub_variant', 'CreatedDate'], name='products_st_sub_var_6840c1_idx'),
        ),
    ]
